name: on-pull-requests-step00
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'step00/**'
      - '.github/workflows/on-pull-requests-step00.yaml'

jobs:
  step00:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./step00
    steps:      
      - name: Setup system Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pyproject.lock','**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-playwright-

      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up virtual environment
        run: uv sync --all-groups 

      - name: Run the app
        run: |
          uv run uvicorn src.screenshotAgent:app --port 9910 &
          sleep 10

      - name: Smoke tests
        run: curl http://localhost:9910/openapi.json -o openapi.json

      - name: Run tests
        run: |
          uv run playwright install
          PYTHONPATH=$PWD uv run pytest tests
