name: when-pr-submitted
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'step00/**'
      - '.github/workflows/on-pull-requests-step00.yaml'

jobs:
  step00:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./step00
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      
      - name: Set up Python
        run: uv python install 3.12

      - name: Set up virtual environment
        run: uv sync --all-groups 

      - name: Run the app
        run: |
          uv run uvicorn src.screenshotAgent:app --port 9910 &
          sleep 10

      - name: Smoke tests
        run: curl http://localhost:9910/openapi.json -o openapi.json

      - name: Run tests
        run: PYTHONPATH=$PWD uv run pytest tests
